name: Android

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 21.0.0.java11

      - name: Install libraries
        run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Gluon Build
        run: mvn -Pandroid client:build client:package
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}

      - name: Make staging directory
        run: mkdir staging

      - name: Copy native clients to staging
        run: cp -r target/client/aarch64-android/gvm/*.apk staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
